spring:
  application:
    name: synchronize

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        highlight_sql: true
#        use_sql_comments: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/synchronize_stock
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 40

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
#      hibernate:
#        orm:
#          jdbc:
#            bind: trace